RazorPages/RazorExamples/Models/Car.cs
namespace razor_pages.Models
{
    public class Car
    {
        public int Id { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public int Year { get; set; }
        public int Doors { get; set; }
        public string Colour { get; set; }
        public decimal Price { get; set; }
    }
}

RazorPages/RazorExamples/Models/PersonModel.cs
using Microsoft.AspNetCore.Mvc;

namespace razor_pages.Models
{
    public class PersonModel
    {
        [BindProperty]
        public string FirstName { get; set; }

        [BindProperty]
        public string LastName { get; set; }
    }
}

RazorPages/RazorExamples/Models/RatingEnum.cs
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace razor_pages.Models
{
    public enum RatingEnum
    {
        Unrated,
        [Display(Name = "1 Star")]
        OneStar,
        [Display(Name = "2 Star")]
        TwoStar,
        [Display(Name = "3 Star")]
        ThreeStar,
        [Display(Name = "4 Star")]
        FourStar,
        [Display(Name = "5 Star")]
        FiveStar
    }
}

RazorPages/RazorExamples/Pages/Examples1/PageModel.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
namespace RazorPages.Pages
{
    public class ExampleModel : PageModel
    {
        [BindProperty]
        public string? Name { get; set; }

        public string? Message { get; set; }
        public void OnGet()
        {
            Message = "Get used";
        }
        public void OnPost()
        {
            Message = "Post used";
        }
    }
}

RazorPages/RazorExamples/Pages/Examples2/PostForm.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using razor_pages.Models;

namespace razor_pages.Pages.Person
{
    public class IndexModel : PageModel
    {
        public string Name { get; set; }

        public void OnGet()
        {
        }

        public void OnPostSubmit(PersonModel person)
        {
            Name = string.Format("Name: {0} {1}", person.FirstName, person.LastName);
        }
    }
}

RazorPages/RazorExamples/Pages/Examples2/ViewDataAttribute.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace razor_pages.Pages.Examples2
{
    public class ViewDataAttributeModel : PageModel
    {
        [ViewData]
        public string Message { get; set; }
        public void OnGet()
        {
            Message = "Hello World";
        }   
    }
}

RazorPages/RazorExamples/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace razor_pages.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

RazorPages/RazorExamples/Pages/examples7/return_json_pagemodel.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Cryptography;

namespace razor_pages.Pages.examples7
{
    public class return_json_pagemodelModel : PageModel
    {
        public void OnGet()
        {

        }
        public async Task<JsonResult> OnGetCarList1()
        {
            return new JsonResult(new { test = "Jack" });
        }
        public async Task<JsonResult> OnPostCarList2([FromForm] string test)
        {
            return new JsonResult(new { test = "Pack" });
        }
    }
}

RazorPages/RazorExamples/Pages/Examples1/PageModel.cshtml
@page
@model ExampleModel
@using RazorPages.Pages
@{
    ViewData["Title"] = "Page Model";
}
<div style="margin-top:30px;">
    <form method="post">
        <div>Name: <input asp-for="Name" /></div>
        <div><input type="submit" /></div>
    </form>
    @if (!string.IsNullOrEmpty(Model.Name))
    {
        <p>Hello @Model.Name!</p>
    }
</div>

<h3>@Model.Message</h3>
<form method="post"><button class="btn btn-default">Click to post</button></form>
<p><a href="/" class="btn btn-default">Click to Get</a></p>

RazorPages/RazorExamples/Pages/Examples1/functions_block.cshtml
@page

@functions {
    [BindProperty]
    public string Name { get; set; }
}

<div style="margin-top:30px;">
    <form method="post">
        <div>Name: <input name="name" /></div>
        <div><input type="submit" /></div>
    </form>
    @if (!string.IsNullOrEmpty(Name))
    {
        <p>Hello @Name!</p>
    }
</div>

RazorPages/RazorExamples/Pages/Examples1/functions_local_method.cshtml
@page
@using Microsoft.AspNetCore.Html;

@functions {
    void DisplayDate(DateTime dt)
    {
        <span class="date">@dt.ToString("dddd, dd MMMM yyyy")</span>
    }
}

@{
    Func<DateTime, IHtmlContent> DisplayDate2 = @<span class="date">@item.ToString("dddd, dd MMMM yyyy")</span>;
}


@{
    DisplayDate(new DateTime(2019, 05, 09, 9, 15, 0));
    <br>
    <br>
    <br>
    DisplayDate2(new DateTime(2023, 05, 09, 9, 15, 0));
}

RazorPages/RazorExamples/Pages/Examples1/razor_syntax.cshtml
@page

@{
    var numbers = Enumerable.Range(1, 10);
}

@foreach (var number in numbers)
{
    @number
}
<br />
@foreach (var number in numbers)
{
    @(number * 10)
}
<br />
For support, contact support@@domain.com
<br />
@*variables with verbatim literal string*@
@foreach (var number in numbers)
{
    @(number * 10)

    @:&nbsp;
}

@*jump from code to html and viceversa*@
@foreach (var number in numbers)
{
    <span>@(number * 10)&nbsp;</span>
}
@*<text>not rendered</text>*@
@foreach (var number in numbers)
{
    <text>@(number * 10) * 10 = @(number * 10)&nbsp;</text>
}

RazorPages/RazorExamples/Pages/Examples1/single_file.cshtml
@page
@{
    var name = string.Empty;
    if (Request.HasFormContentType)
    {
        name = Request.Form["name"];
    }
}
<div style="margin-top:30px;">
    <form method="post">
        <div>Name: <input name="name" /></div>
        <div><input type="submit" /></div>
    </form>
</div>
<div>
    @if (!string.IsNullOrEmpty(name))
    {
        <p>Hello @name!</p>
    }
</div>

RazorPages/RazorExamples/Pages/Examples2/PostForm.cshtml
@page
@addTagHelper*, Microsoft.AspNetCore.Mvc.TagHelpers
@model razor_pages.Pages.Person.IndexModel

@{
    ViewData["Title"] = "Index";
}
<form method="post">
    <table>
        <tr>
            <td>First Name: </td>
            <td><input type="text" id="txtFirstName" name="FirstName" /></td>
        </tr>
        <tr>
            <td>Last Name: </td>
            <td><input type="text" id="txtLastName" name="LastName" /></td>
        </tr>
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Submit" asp-page-handler="Submit" />
            </td>
        </tr>
    </table>
    <hr />
    @Model.Name
</form>

RazorPages/RazorExamples/Pages/Examples2/ViewDataAttribute.cshtml
@page
@model ViewDataAttributeModel
@{

}
<h2>@Model.Message from Model.Message</h2>
<h2>@ViewData["Message"] from ViewData["Message"]</h2>

<partial name="_HelloWorldPartial" />

RazorPages/RazorExamples/Pages/Examples2/_HelloWorldPartial.cshtml
<p>@ViewData["Message"] from the Hello World partial</p>

RazorPages/RazorExamples/Pages/Examples2/multi_action_form.cshtml
@*@page*@
@page "{handler?}"
@functions {
    public string Message { get; set; } = "Initial Request";
    public void OnPostRegister()
    {
        Message = "from OnPostRegister";
    }
    public void OnPostRequestInfo()
    {
        Message = "from OnPostRequestInfo";
    }
}

<form method="post">
    <button asp-page-handler="Register">Register Now</button>
    <button asp-page-handler="RequestInfo">Request Info</button>
</form>
<h3 class="clearfix">@Model.Message</h3>

RazorPages/RazorExamples/Pages/Examples2/named_page_handler.cshtml
@*@page *@
@page "{handler?}"
@functions {
    public string Message { get; set; } = "Initial Request";
    public void OnGet()
    {
    }
    public void OnPost()
    {
        Message = "Form Posted";
    }
    public void OnPostDelete()
    {
        Message = "Delete handler fired";
    }
    public void OnPostEdit(int id)
    {
        Message = "Edit handler fired";
    }
    public void OnPostView(int id)
    {
        Message = $"View handler fired for {id}";
    }
}

<div class="row">
    <div class="col-lg-1">
        <form asp-page-handler="edit" method="post">
            <button class="btn btn-default">Edit</button>
        </form>
    </div>
    <div class="col-lg-1">
        <form asp-page-handler="delete" method="post">
            <button class="btn btn-default">Delete</button>
        </form>
    </div>
    <div class="col-lg-1">
        <form asp-page-handler="view" method="post">
            <button class="btn btn-default">View</button>
            <input type="hidden" name="id" value="3" />
        </form>
    </div>
</div>
<h3 class="clearfix">@Model.Message</h3>

RazorPages/RazorExamples/Pages/Examples2/view_bag.cshtml
@page
@{
    @functions {
        public void OnGet()
        {
            ViewBag.Title = "My Home Page";
        }
    }
}
<h1>@ViewBag.Title from ViewBag.Title</h1>
<h2>@ViewData["Title"] from ViewData["Title"]</h2>

RazorPages/RazorExamples/Pages/Examples2/view_data.cshtml
@page
@{
    @functions {
        public void OnGet()
        {
            ViewData["MyNumber"] = 42;
            ViewData["MyString"] = "Hello World";
            ViewData["MyComplexObject"] = new Book("Sum Of All Fears", new Author("Tom Clancy"), 5.99m);
        }
        record Book(string Title, Author Author, decimal Price);
        record Author(string Name);
    }
}
<h2>@ViewData["MyString"]</h2>
<p>The answer to everything is @ViewData["MyNumber"]</p>
@{
    Book? book = (Book?)ViewData["MyComplexObject"];
}
<h2>@book?.Title</h2>
<p>@book?.Author.Name</p>
<p>@book?.Price</p>