Toasts/PopupNotifications/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace popup_notifications.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(string name)
        {
            ViewBag.Message = string.Format("Hello {0}.\\nCurrent Date and Time: {1}", name, DateTime.Now.ToString());
            return View();
        }
    }
}

Toasts/PopupNotifications/Controllers/JqueryNotifyController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace popup_notifications.Controllers
{
    public class JqueryNotifyController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(string test)
        {
            Console.WriteLine("Hello from console");
            Debug.WriteLine("hello from debug");
            TempData["Message"] = " Customer updated successfully.";
            return View();
        }
    }
}

Toasts/PopupNotifications/Controllers/ModalPopupController.cs
using Microsoft.AspNetCore.Mvc;

namespace popup_notifications.Controllers
{
    public class ModalPopupController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public  IActionResult Success()
        {
            TempData["Success"] = "Something is successful";
            return RedirectToAction("Index");
        }
        public IActionResult Info()
        {
            TempData["Info"] = "Info about something";
            return RedirectToAction("Index");
        }
        public IActionResult Error()
        {
            TempData["Error"] = "Some error happened";
            return RedirectToAction("Index");
        }
    }
}

Toasts/PopupNotifications/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Aspnet.JQuery</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/jquery-ui.min.css" rel="stylesheet" />
</head>
<body>
    <div class="row m-1 p-1">
        <div id="categories" class="col-2">
            <div class="d-grid gap-2">
                <a class="btn btn-secondary" asp-action="Index" asp-controller="Home">
                   AlertViewbagMessage
                </a>
                <a class="btn btn-secondary" asp-action="Index" asp-controller="JqueryNotify">
                    JqueryNotify
                </a>
                <a class="btn btn-secondary" asp-action="Index" asp-controller="ModalPopup">
                    ModalPopup
                </a>
            </div>
        </div>
        <div class="col-10">
            @RenderBody()
        </div>
        <div id="_SiteScripts" class="hidden">
            <script src="~/js/jquery.min.js"></script>
            <script src="~/js/jquery-ui.min.js"></script>
            <script src="~/js/bootstrap.min.js"></script>
            <script src="~/js/jquery.validate.min.js"></script>
            <script src="~/js/jquery.validate.unobtrusive.min.js"></script>
            <script src="~/js/notify.js"></script>
        </div>
        @await RenderSectionAsync("Scripts", required: false)
        <partial name="_Notification" />
    </div>
</body>
</html>

Toasts/PopupNotifications/Views/Shared/_Notification.cshtml
@if (TempData["Success"] != null)
{
    <input type="hidden" id="modal" value="#successModal" />
    <partial name="/Views/Shared/Notifications/_Success.cshtml" model="(string?)@TempData["Success"]" />
}
@if (TempData["Error"] != null)
{
    <input type="hidden" id="modal" value="#errorModal" />
    <partial name="/Views/Shared/Notifications/_Error.cshtml" model="(string?)@TempData["Error"]" />
}
@if (TempData["Info"] != null)
{
    <input type="hidden" id="modal" value="#infoModal" />
    <partial name="/Views/Shared/Notifications/_Info.cshtml" model="(string?)@TempData["Info"]" />
}
<script>
    $(function () {
        var showModal = $('#modal').val();
        if (typeof showModal !== 'undefined') {
            $(showModal).modal('show');
        }
    });
</script>